### ISSUE TITLE
Determine total number of different case formats or outlines.

### ISSUE THREAD

**Issue by kendallwerts** [codefortulsa/oscn#13]
and provide a link to a good example for each.

There are at least 2. Are there any more?

**Comment by jwhitlock** [comment]
I was looking at the entries for foreclosure cases a few years ago, and I found that the entries for Tulsa County foreclosure cases follow a similar format, but that some of the smaller counties have different formats, and some are basically PDF uploads. At a higher level, the case formats may be the same, just what the clerks enter would vary.

**Comment by jdungan** [comment]
Full list on http://www.oscn.net/dockets/Search.aspx.
