### ISSUE TITLE
throw an error when case is not found

### ISSUE THREAD

**Issue by groovecoder** [codefortulsa/oscn#21]
When calling code tries to get a case number that can't be found, throw an error.

STR:
```
In [3]: case = oscn.request.Case(county='tulsa', year='2018', number='CV-2018-1217')

In [4]: case.events
Out[4]: []

In [5]: case.docket
Out[5]: []

In [6]: case.attorneys
Out[6]: []

In [7]: case.counts
Out[7]: []
```

Expected results:
The call to `oscn.request.Case` should throw an error since the case number can't be found.

Actual results:
The case object is returned, but completely empty.

**Comment by jdungan** [comment]
OSCN returns OK even on unused case numbers.  There are also case numbers that return OK but say things like THIS CASE NUMBER WAS NOT USED.  Case checks for these instances and returns with a property called 'valid' that you can check.

**Comment by kendallwerts** [comment]
I think it should definitely throw an error. You can feed it bad info and it will still return ok. i.e.: https://github.com/codefortulsa/courtbot-python/issues/44#issuecomment-546718397 

I was looking at this a little this weekend. I can try to see what I can do later this week.

**Comment by jdungan** [comment]
It fails silently so you can process lists. There is a .valid property that
you can test.
