### ISSUE TITLE
oscn.request.Case: Default to search across all counties

### ISSUE THREAD

**Issue by groovecoder** [codefortulsa/oscn#22]
When I call `oscn.request.Case(number=case_num)`, I want it to return a case no matter what year or county it is. If there are multiple matches, return a list of cases.

**Comment by jdungan** [comment]
There's a 'counties' property on ocsn that returns a list of all counties.

This should do what you want:
```
all_counties = oscn.counties
years = ['2019', '2018']
types=['CF', 'CM']

oscn.request.CaseList(counties=all_counties, years=years, types=types, number=123)
```

**Comment by groovecoder** [comment]
Cool, I'll use that for now. But a new method that automates that for calling code would be helpful, so I'll leave this issue open too.

**Comment by jdungan** [comment]
Stay tuned for oscn.find ...

**Comment by jdungan** [comment]
@groovecoder check out the new .find.CaseIndexes to see if this issue can be closed.
