### ISSUE TITLE
Case number lower case unable to find case

### ISSUE THREAD

**Issue by syk1112** [codefortulsa/oscn#25]
- `case = oscn.request.Case(year='2019', county='tulsa', number='cf-2019-123')` - `.events` does not work
- `case = oscn.request.Case(year='2019', county='tulsa', number='CF-2019-123')` - `.events` works
- `case = oscn.request.Case(year='2019', county='Tulsa', number='CF-2019-123')` - `.events` works

As mentioned above, when the case number is lower cased it is unable to find events (case not found)

**Comment by jdungan** [comment]
The 'type' can't be included with the number.   Each element needs to be an argument. Here's a working version:

`case = oscn.request.Case(year='2019', county='tulsa', type='cf', number=123)`

or this works too:

`case = oscn.request.Case('tulsa-cf-2019-123')'
