### ISSUE TITLE
oscn api documentation

### ISSUE THREAD

**Issue by jdungan** [codefortulsa/oscn#8]
Need some help and suggestions for documenting the functions and behaviors.

**Comment by Chromaticdeth19XX** [comment]
Resources from session on 6.17.2018:
http://www1.odcr.com/
Description of information found:
*cricket chirps*

Discussion:
@jdungan explained a few of the scripts that aid in the scraping of the OSCN html on a given page. 
Github issues were discussed and volunteers were asked to pick an issue to take ownership of its completion. 

Scope of the scraper was defined for the short term:
oscn > This is python package to provide a utility for retrieving and parsing case records.
 

Short Term goal for the user interface:
The parser(s) returns human readable data for easy consumption. Well formed, well defined parsers that give the end user a clean set of data. one page of OSCN data at a time 

End of working session 7.16.2018

Demonstration of the OSCN-Query application through the CL interface. 

Note to self**: Syntax needs to be documented for the CL interface. UI has met with some interesting ideas among the group But, the parser needs to be decoupled from any of the peripheral
