### ISSUE TITLE
Add __utf8__ method to docket

### ISSUE THREAD

**Issue by groovecoder** [codefortulsa/oscn#9]

**Comment by julia-codes** [comment]
Dockets need a better print format

Printing out all dockets on a case looks like this. Needs some kind of 'Prettier' method to show all the DocketEvents on a docket
[{'case_number': 'CM-###-1', 'docket': [<oscn.parse.docket.DocketEvent object at 0x7f30e8b30a20>, <oscn.parse.docket.DocketEvent object at 0x7f30e8b309e8>, <oscn.parse.docket.DocketEvent object at 0x7f30e8b30a90>]}]

**Comment by jdungan** [comment]
OBE. All properties are now str or dictionaires.
